print("=====================================") 
print("= NAMA    : Muhammad Rifai Aditia    ") 
print("= NIM     : 312010065                ") 
print("= KELAS   : TI.20 A.1                ") 
print("=====================================") 

print("Please enter your full name : Muhammad Rifai Aditia")
fullname=input() 
print("Please enter nickname : Radit")
nickname=input() 
print("Please enter your NPM : 312010065")
npm=input() 
print("Please enter place of birth : Ponorogo")  
pob=input() 
print("Please enter date of birth : 08")
date=input() 
print("Please enter your month of birth : Januari")  
month=input() 
print("Please enter year of birth : 2002")  
year=input()                                                                                                                                             
print("Please enter your phone number : 0895320208010") 
phone=input()
print("Please enter your address : Perumahan Rusa") 
address=input()

dob=input("2020-year")

print("\n\n Assalamu'alaikum. ")
print("f\n Let me introduce my self, my name is {Muhammad Rifai Aditia}, but you can call me {Radit}, my NPM {312010065}, I was born in {Ponorogo} and iam {2020} years old, I am very glad if you want to invite my house in {Perumahan Rusa}, So don't forget to call me before with the number {0895320208010}, \n\n Thanks you very much ")